# Generated by Django 4.0.4 on 2022-04-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='text',
            new_name='Text',
        ),
    ]
